export interface ProfileType {
    _id: string,
  created_at: string,
  modified_at: string,
  suggestion_reject: any [],
  location_status: boolean,
  sync_contacts: boolean,
  email_status: boolean,
  name_status: boolean,
  gender_status: boolean,
  bio_status: boolean,
  referal_status: boolean,
  bio: any [],
  visibility: string,
  role: string,
  past_convos: any [],
  followers: any [],
  following: any [],
  requests: any [],
  sent_requests: any [],
  mute: any [],
  device_id: any [],
  sports_interest: any [],
  activity_log: any [],
  update_status: boolean,
  status: boolean,
  ignored_suggestions: any [],
  coins: number,
  refer_id: string,
  phone: string,
  otp: number,
  handle: string,
  temporary: boolean,
  conversation: any [],
  clubs: any [],
  __v: number,
  email: string,
  history: {
    football: { game: number, mvp: number },
    basketball: { game: number, mvp: number },
    cricket: { game: number, mvp: number },
    badminton: { game: number, mvp: number }
  },
  name: string,
  password: string,
  online_status: string,
  device_token: string,
  os: string,
  version: string,
  location: {
    lng: string,
    village: string,
    subSubLocality: string,
    district: string,
    city: string,
    pincode: string,
    area: string,
    lat: string,
    state: string,
  },
  last_active: string,
  last_login: string,
  profile_picture: string,
  fav_sports: any [],
  sport_status: boolean,
  signup_status: boolean,
  device_tokens: any [],
  channel: any [],
  fav_venues: any [],
  games_month: number,
  hosted_game: number,
  played_with: number,
  reward_claimed: number,
  total_games: number
}