import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from '../../components/Banner'
import Card from '../../components/Card/Card'
//data
import coffeeStoreData from '../../data/coffee-stores.json'
import { Key } from 'react'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps(context: any) {
  return {
    props: { coffeeStore: coffeeStoreData }, // will be passed to the page component as props
  }
}

export default function Home(props: { coffeeStore: any[] }) {
  const handleOnClick = () => {
    console.log("button click");
  }
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <Banner buttonText={"View stores nearby"} onClick={handleOnClick} />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" alt={''} width={700} height={400} />
        </div>
        {props.coffeeStore.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStore.map((item: { id: any; name: string; imgUrl: string }, index: Key | null | undefined) => (

                <Card key={index} href={`/coffee-store/${item.id}`} title={item.name} imgUrl={item.imgUrl} />
              ))}

            </div>
          </>
        )}



      </main>
    </>
  )
}
